dpkg -b cn.agricu.afc2d-arm64_1.1_iphoneos-arm
dpkg -b cn.agricu.AlipayForest_2.0.0_iphoneos-arm
dpkg -b cn.agricu.appstoreplusplus_0.9.10_iphoneos-arm
dpkg -b cn.agricu.appsyncunified_70.0_iphoneos-arm
dpkg -b cn.agricu.crackerxi_1.1.16_iphoneos-arm
dpkg -b cn.agricu.cydown_7.0.9_iphoneos-arm
dpkg -b cn.agricu.dismissprogress_1.0.3_iphoneos-arm
dpkg -b cn.agricu.GestureX_1.0.4_iphoneos-arm
dpkg -b cn.agricu.locationhelper_5.3.10_iphoneos-arm
dpkg -b cn.agricu.newterm2_2.4_iphoneos-arm
dpkg -b cn.agricu.realcc_1.0.2_iphoneos-arm
dpkg -b cn.agricu.renet_1.1_iphoneos-arm
dpkg -b cn.agricu.shadow_2.0.20_iphoneos-arm
dpkg -b cn.agricu.shutup_1.0.1_iphoneos-arm
dpkg -b cn.agricu.spotlightless11_1.1.3_iphoneos-arm
dpkg -b cn.agricu.theos_1.0.3_iphoneos-arm
dpkg -b cn.agricu.tsssaver2_1.0-beta-4.2_iphoneos-arm
dpkg -b cn.agricu.unc0ver_4.3.1_iphoneos-arm
dpkg -b cn.agricu.virtualstep_1.0.0_iphoneos-arm
dpkg -b cn.agricu.vsz.redeb_1.0.3_iphoneos-arm
dpkg -b cn.Agricu.WebRefresher_1.0.1_iphoneos-arm
dpkg -b cn.agricu.wifipasswords_3.0.1_iphoneos-arm
dpkg -b com.tigisoftware.filza64bit_3.7.4-12_iphoneos-arm
dpkg -b com.xybp888.CallAssist13_1.2.2_iphoneos-arm